version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command:  bash -c "rm --f build && go build -o build && ./build"
    volumes:
    - .:/go/src/github.com/dobrovolsky/money_bot/
    working_dir: /go/src/github.com/dobrovolsky/money_bot/
    depends_on:
      - stats

  stats:
    build:
      context: stats
      dockerfile: Dockerfile
    command: bash -c "poetry run python ploting/server.py"
    volumes:
    - ./stats:/code