version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command:  ./docker_entrypoint.sh
    volumes:
    - .:/go/src/github.com/dobrovolsky/moneybot/
    - cache:/go
    working_dir: /go/src/github.com/dobrovolsky/moneybot/
    depends_on:
      - stats

  stats:
    build:
      context: stats
      dockerfile: Dockerfile
    command: bash -c "poetry run python ploting/server.py"
    volumes:
    - ./stats:/code

volumes:
  cache:
