version: '3.7'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd /go/src/money/ && rm build && go build -o build"
    volumes:
    - .:/go/src/money

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command:  bash -c "cd /go/src/money/ && rm build && go build -o build && ./build"
    volumes:
    - .:/go/src/money
